--Insert Inicial Taxas
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (500, 1001, 0.65)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (1001, 10000, 0.85)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (10001, 20000, 0.98)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (20001, null, 1.018)


--Insert Inicial Taxas
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (500, 1001, 0.65)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (1001, 10000, 0.85)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (10001, 20000, 0.98)
insert into TAXA (VALOR_INICIAL,VALOR_FINAL,PERCENTUAL) values (20001, null, 1.018)

--Insert Inicial Produtos
insert into PRODUTO (DESCRICAO, DT_VENCIMENTO, DT_CADASTRO, VALOR_UNITARIO) values ('Produto 1',DATEADD(year, 1, GETDATE()) ,GETDATE(), 500)
insert into PRODUTO (DESCRICAO, DT_VENCIMENTO, DT_CADASTRO, VALOR_UNITARIO) values ('Produto 2',DATEADD(year, 2, GETDATE()) ,GETDATE(), 8000)
insert into PRODUTO (DESCRICAO, DT_VENCIMENTO, DT_CADASTRO, VALOR_UNITARIO) values ('Produto 3',DATEADD(year, 3, GETDATE()) ,GETDATE(), 12000)
insert into PRODUTO (DESCRICAO, DT_VENCIMENTO, DT_CADASTRO, VALOR_UNITARIO) values ('Produto 4',DATEADD(year, 4, GETDATE()) ,GETDATE(), 22000)