// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CmCapitalSalesAvaliacao.Domain.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Pedido = new HashSet<Pedido>();
        }

        public long CdCliente { get; set; }
        public string Nome { get; set; }
        public DateTime? DtUltimaCompra { get; set; }
        public decimal Saldo { get; set; }

        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}