// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CmCapitalSalesAvaliacao.Domain.Models
{
    public partial class Pedido
    {
        public Pedido()
        {
            PedidoItem = new HashSet<PedidoItem>();
        }

        public long CdPedido { get; set; }
        public long CdCliente { get; set; }
        public DateTime DtPedido { get; set; }
        public byte Status { get; set; }

        public virtual Cliente CdClienteNavigation { get; set; }
        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}