// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CmCapitalSalesAvaliacao.Domain.Models
{
    public partial class Produto
    {
        public Produto()
        {
            PedidoItem = new HashSet<PedidoItem>();
        }

        public int CdProduto { get; set; }
        public string Descricao { get; set; }
        public DateTime DtVencimento { get; set; }
        public DateTime DtCadastro { get; set; }
        public decimal ValorUnitario { get; set; }

        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}