// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CmCapitalSalesAvaliacao.Domain.Models
{
    public partial class Taxa
    {
        public int CdTaxa { get; set; }
        public decimal ValorInicial { get; set; }
        public decimal? ValorFinal { get; set; }
        public double Percentual { get; set; }
    }
}