CREATE TABLE [dbo].[PEDIDO_ITEM]
(
	[CD_PEDIDO_ITEM] BIGINT NOT NULL PRIMARY KEY, 
    [CD_PEDIDO] BIGINT NOT NULL, 
    [CD_PRODUTO] INT NOT NULL, 
    [NR_QUANTIDADE] INT NOT NULL, 
    [VALOR_TOTAL] MONEY NOT NULL
)
