CREATE TABLE [dbo].[PEDIDO]
(
	[CD_PEDIDO] BIGINT NOT NULL, 
    [CD_CLIENTE] BIGINT NOT NULL, 
    [DT_PEDIDO] DATETIME NOT NULL, 
    [STATUS] TINYINT NOT NULL

    CONSTRAINT PK_PEDIDO PRIMARY KEY NONCLUSTERED ([CD_PEDIDO]),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY ([CD_CLIENTE]) REFERENCES CLIENTE([CD_CLIENTE])
)
