CREATE TABLE [dbo].[PEDIDO]
(
	[CD_PEDIDO] BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [CD_CLIENTE] BIGINT NOT NULL, 
    [DT_PEDIDO] DATETIME NOT NULL, 
    [STATUS] TINYINT NOT NULL,

    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY ([CD_CLIENTE]) REFERENCES CLIENTE([CD_CLIENTE])
)
